/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include <memory>

#include <gtest/gtest.h>

#include <Creators.h>
#include <DexClass.h>
#include <IRInstruction.h>

#include <mariana-trench/TransferCall.h>
#include <mariana-trench/tests/Test.h>

namespace marianatrench {

namespace {

// There is no end-to-end coverage for this: an encoded static value only
// exists for a `static final` primitive or String with a constant initializer,
// and javac folds every read of exactly those into the use site. The shape only
// arises in generated bytecode, so the field has to be built directly.
DexField* create_static_field(
    const std::string& class_name,
    const std::string& field_name,
    DexType* type,
    std::unique_ptr<DexEncodedValue> value,
    DexAccessFlags access = static_cast<DexAccessFlags>(ACC_STATIC | ACC_FINAL),
    bool with_class_initializer = false) {
  ClassCreator creator(DexType::make_type(class_name));
  creator.set_super(type::java_lang_Object());
  auto* field = static_cast<DexField*>(DexField::make_field(
      DexType::make_type(class_name),
      DexString::make_string(field_name),
      type));
  field->make_concrete(access, std::move(value));
  creator.add_field(field);
  if (with_class_initializer) {
    auto* clinit = static_cast<DexMethod*>(DexMethod::make_method(
        DexType::make_type(class_name),
        DexString::make_string("<clinit>"),
        DexProto::make_proto(type::_void(), DexTypeList::make_type_list({}))));
    clinit->make_concrete(
        static_cast<DexAccessFlags>(ACC_STATIC | ACC_CONSTRUCTOR),
        std::make_unique<DexCode>(),
        /* is_virtual */ false);
    creator.add_method(clinit);
  }
  creator.create();
  return field;
}

std::unique_ptr<IRInstruction> sget_of(DexField* field, IROpcode opcode) {
  auto instruction = std::make_unique<IRInstruction>(opcode);
  instruction->set_field(field);
  return instruction;
}

} // namespace

class StaticFieldConstantTest : public test::Test {};

TEST_F(StaticFieldConstantTest, ResolvesStaticFinalLong) {
  auto* field = create_static_field(
      "LResolvesStaticFinalLong;",
      "specifier",
      type::_long(),
      std::make_unique<DexEncodedValuePrimitive>(
          DEVT_LONG, static_cast<uint64_t>(0x82004501ae0154L)));

  auto instruction = sget_of(field, OPCODE_SGET_WIDE);

  EXPECT_EQ(
      static_final_field_constant(instruction.get()),
      std::optional<std::string>(std::to_string(0x82004501ae0154L)));
}

TEST_F(StaticFieldConstantTest, ResolvesStaticFinalInt) {
  auto* field = create_static_field(
      "LResolvesStaticFinalInt;",
      "count",
      type::_int(),
      std::make_unique<DexEncodedValuePrimitive>(DEVT_INT, 1234));

  auto instruction = sget_of(field, OPCODE_SGET);

  EXPECT_EQ(
      static_final_field_constant(instruction.get()),
      std::optional<std::string>("1234"));
}

TEST_F(StaticFieldConstantTest, ResolvesStaticFinalString) {
  auto* field = create_static_field(
      "LResolvesStaticFinalString;",
      "name",
      type::java_lang_String(),
      std::make_unique<DexEncodedValueString>(
          DexString::make_string("some-config")));

  auto instruction = sget_of(field, OPCODE_SGET_OBJECT);

  EXPECT_EQ(
      static_final_field_constant(instruction.get()),
      std::optional<std::string>("some-config"));
}

TEST_F(StaticFieldConstantTest, IgnoresMutableStaticField) {
  // A non-final static can be written after `<clinit>`, so its encoded value is
  // not what the read observes.
  auto* field = create_static_field(
      "LIgnoresMutableStaticField;",
      "mutable_specifier",
      type::_long(),
      std::make_unique<DexEncodedValuePrimitive>(DEVT_LONG, 4321),
      ACC_STATIC);

  auto instruction = sget_of(field, OPCODE_SGET_WIDE);

  EXPECT_EQ(static_final_field_constant(instruction.get()), std::nullopt);
}

TEST_F(StaticFieldConstantTest, IgnoresFieldInClassWithClassInitializer) {
  // `DexField::set_value` normalizes an absent encoded value to zero-for-type,
  // so a field assigned in `<clinit>` looks identical to one encoded as 0.
  // Without the `<clinit>` guard this would resolve to "0" and feed a wrong
  // constant into a `via_value_of` feature.
  auto* field = create_static_field(
      "LIgnoresFieldInClassWithClassInitializer;",
      "computed",
      type::_long(),
      /* value */ nullptr,
      static_cast<DexAccessFlags>(ACC_STATIC | ACC_FINAL),
      /* with_class_initializer */ true);

  auto instruction = sget_of(field, OPCODE_SGET_WIDE);

  EXPECT_EQ(static_final_field_constant(instruction.get()), std::nullopt);
}

TEST_F(StaticFieldConstantTest, NullEncodedValueIsNormalizedToZero) {
  // Documents the Redex behaviour the guard above exists for. Were this to
  // change, the guard could be relaxed.
  auto* field = create_static_field(
      "LNullEncodedValueIsNormalizedToZero;",
      "computed",
      type::_long(),
      /* value */ nullptr);

  EXPECT_NE(field->get_static_value(), nullptr);
  EXPECT_EQ(field->get_static_value()->value(), 0u);
}

TEST_F(StaticFieldConstantTest, IgnoresNonFieldInstruction) {
  auto instruction = std::make_unique<IRInstruction>(OPCODE_CONST_WIDE);
  instruction->set_literal(7);

  EXPECT_EQ(static_final_field_constant(instruction.get()), std::nullopt);
}

TEST_F(StaticFieldConstantTest, IgnoresInstanceFieldRead) {
  auto* field = create_static_field(
      "LIgnoresInstanceFieldRead;",
      "instance_specifier",
      type::_long(),
      std::make_unique<DexEncodedValuePrimitive>(DEVT_LONG, 99));

  // `iget*` has one source register, which is what distinguishes it here.
  auto instruction = sget_of(field, OPCODE_IGET_WIDE);
  instruction->set_srcs_size(1);
  instruction->set_src(0, 0);

  EXPECT_EQ(static_final_field_constant(instruction.get()), std::nullopt);
}

TEST_F(StaticFieldConstantTest, IdentityForStaticFinalObjectField) {
  // The FB4A shape: a wrapper object built in `<clinit>` and read back with
  // `sget-object`. There is no value to read, so the field names it.
  auto* field = create_static_field(
      "LIdentityForStaticFinalObjectField;",
      "specifier",
      DexType::make_type("Lcom/example/Specifier;"),
      /* value */ nullptr,
      static_cast<DexAccessFlags>(ACC_STATIC | ACC_FINAL),
      /* with_class_initializer */ true);

  auto instruction = sget_of(field, OPCODE_SGET_OBJECT);

  EXPECT_EQ(
      static_final_field_identity(instruction.get()),
      std::optional<std::string>(
          "LIdentityForStaticFinalObjectField;.specifier"));
}

TEST_F(StaticFieldConstantTest, IdentityIgnoresArrayField) {
  // Array element reads are index-insensitive in the alias analysis, so
  // `TABLE[i]` shares a memory location with `TABLE`. Naming the field would
  // claim the argument is the array when it is one unknown element of it.
  auto* field = create_static_field(
      "LIdentityIgnoresArrayField;",
      "table",
      DexType::make_type("[J"),
      /* value */ nullptr);

  auto instruction = sget_of(field, OPCODE_SGET_OBJECT);

  EXPECT_EQ(static_final_field_identity(instruction.get()), std::nullopt);
}

TEST_F(StaticFieldConstantTest, IdentityIgnoresMutableObjectField) {
  auto* field = create_static_field(
      "LIdentityIgnoresMutableObjectField;",
      "specifier",
      DexType::make_type("Lcom/example/Specifier;"),
      /* value */ nullptr,
      ACC_STATIC);

  auto instruction = sget_of(field, OPCODE_SGET_OBJECT);

  EXPECT_EQ(static_final_field_identity(instruction.get()), std::nullopt);
}

TEST_F(StaticFieldConstantTest, IdentityDefersToConstantForPrimitives) {
  // A primitive has a real value, which is strictly more informative than the
  // field name, so the identity path declines it.
  auto* field = create_static_field(
      "LIdentityDefersToConstantForPrimitives;",
      "specifier",
      type::_long(),
      std::make_unique<DexEncodedValuePrimitive>(DEVT_LONG, 17));

  auto instruction = sget_of(field, OPCODE_SGET_WIDE);

  EXPECT_EQ(static_final_field_identity(instruction.get()), std::nullopt);
  EXPECT_EQ(
      static_final_field_constant(instruction.get()),
      std::optional<std::string>("17"));
}

} // namespace marianatrench
